-- MySQL Script generated by MySQL Workbench
-- Wed 09 Oct 2024 06:47:12 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pufPlatformDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pufPlatformDB` ;

-- -----------------------------------------------------
-- Schema pufPlatformDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pufPlatformDB` ;
USE `pufPlatformDB` ;

-- -----------------------------------------------------
-- Table `pufPlatformDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pufPlatformDB`.`User` ;

CREATE TABLE IF NOT EXISTS `pufPlatformDB`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `affiliation` VARCHAR(45) NULL,
  `recordDate` DATE NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pufPlatformDB`.`Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pufPlatformDB`.`Device` ;

CREATE TABLE IF NOT EXISTS `pufPlatformDB`.`Device` (
  `idDevice` INT NOT NULL AUTO_INCREMENT,
  `macAddress` VARCHAR(17) NOT NULL,
  `ipAddress` VARCHAR(15) NOT NULL,
  `vendor` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `fpga` TINYTEXT NOT NULL,
  `state` ENUM('available', 'unavailable', 'ready', 'unreachable') NOT NULL,
  `usedBy` INT NULL,
  PRIMARY KEY (`idDevice`, `macAddress`),
  INDEX `fk_Device_User_idx` (`usedBy` ASC) VISIBLE,
  UNIQUE INDEX `idDevice_UNIQUE` (`idDevice` ASC) VISIBLE,
  UNIQUE INDEX `macAddress_UNIQUE` (`macAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Device_User1`
    FOREIGN KEY (`usedBy`)
    REFERENCES `pufPlatformDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pufPlatformDB`.`PufsConfiguration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pufPlatformDB`.`PufsConfiguration` ;

CREATE TABLE IF NOT EXISTS `pufPlatformDB`.`PufsConfiguration` (
  `idPufsConfiguration` INT NOT NULL AUTO_INCREMENT,
  `createdBy` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idPufsConfiguration`),
  INDEX `fk_PufsConfiguration_User1_idx` (`createdBy` ASC) VISIBLE,
  CONSTRAINT `fk_PufsConfiguration_User1`
    FOREIGN KEY (`createdBy`)
    REFERENCES `pufPlatformDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pufPlatformDB`.`ExpsConfiguration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pufPlatformDB`.`ExpsConfiguration` ;

CREATE TABLE IF NOT EXISTS `pufPlatformDB`.`ExpsConfiguration` (
  `idExpsConfiguration` INT NOT NULL AUTO_INCREMENT,
  `pufsConfiguration` INT NOT NULL,
  `createdBy` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idExpsConfiguration`),
  INDEX `fk_ExpsConfiguration_PufsConfiguration1_idx` (`pufsConfiguration` ASC) VISIBLE,
  INDEX `fk_ExpsConfiguration_User1_idx` (`createdBy` ASC) VISIBLE,
  CONSTRAINT `fk_ExpsConfiguration_PufsConfiguration1`
    FOREIGN KEY (`pufsConfiguration`)
    REFERENCES `pufPlatformDB`.`PufsConfiguration` (`idPufsConfiguration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExpsConfiguration_User1`
    FOREIGN KEY (`createdBy`)
    REFERENCES `pufPlatformDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pufPlatformDB`.`Campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pufPlatformDB`.`Campaign` ;

CREATE TABLE IF NOT EXISTS `pufPlatformDB`.`Campaign` (
  `idCampaign` INT NOT NULL AUTO_INCREMENT,
  `conductedBy` INT NOT NULL,
  `deviceUsed` INT NOT NULL,
  `expsConfiguration` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`idCampaign`),
  UNIQUE INDEX `idCampaign_UNIQUE` (`idCampaign` ASC) VISIBLE,
  INDEX `fk_Campaign_Device1_idx` (`deviceUsed` ASC) VISIBLE,
  INDEX `fk_Campaign_User1_idx` (`conductedBy` ASC) VISIBLE,
  INDEX `fk_Campaign_ExpsConfiguration1_idx` (`expsConfiguration` ASC) VISIBLE,
  CONSTRAINT `fk_Campaign_Device1`
    FOREIGN KEY (`deviceUsed`)
    REFERENCES `pufPlatformDB`.`Device` (`idDevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Campaign_User1`
    FOREIGN KEY (`conductedBy`)
    REFERENCES `pufPlatformDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Campaign_ExpsConfiguration1`
    FOREIGN KEY (`expsConfiguration`)
    REFERENCES `pufPlatformDB`.`ExpsConfiguration` (`idExpsConfiguration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pufPlatformDB`.`CRP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pufPlatformDB`.`CRP` ;

CREATE TABLE IF NOT EXISTS `pufPlatformDB`.`CRP` (
  `idCRP` INT NOT NULL AUTO_INCREMENT,
  `expCampaign` INT NOT NULL,
  `idPuf` INT NOT NULL,
  `numRep` INT NOT NULL,
  `challenge` VARCHAR(256) NOT NULL,
  `response` VARCHAR(256) NOT NULL,
  `temperature` DECIMAL(4,2) NULL,
  `voltage` DECIMAL(5,3) NULL,
  `counter1` VARCHAR(256) NULL,
  `counter2` VARCHAR(256) NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`idCRP`),
  INDEX `fk_CRP_Campaign_idx` (`expCampaign` ASC) VISIBLE,
  CONSTRAINT `fk_CRP_Campaign1`
    FOREIGN KEY (`expCampaign`)
    REFERENCES `pufPlatformDB`.`Campaign` (`idCampaign`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
